// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForDiscord(arg1) {
  return window['go']['backend']['Dialogs']['BrowseForDiscord'](arg1);
}

export function ConfirmAction(arg1, arg2) {
  return window['go']['backend']['Dialogs']['ConfirmAction'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['backend']['Dialogs']['SetContext'](arg1);
}

export function ShowNotice(arg1, arg2, arg3) {
  return window['go']['backend']['Dialogs']['ShowNotice'](arg1, arg2, arg3);
}
