// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function BrowseForDiscord(arg1:string):Promise<string>;

export function ConfirmAction(arg1:string,arg2:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function ShowNotice(arg1:string,arg2:string,arg3:string):Promise<string>;
