// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDiscordPath(arg1) {
  return window['go']['backend']['Paths']['GetDiscordPath'](arg1);
}

export function SetContext(arg1) {
  return window['go']['backend']['Paths']['SetContext'](arg1);
}
