// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BrowseForDiscord(schannel: string): $CancellablePromise<string> {
    return $Call.ByID(413498952, schannel);
}

export function ConfirmAction(title: string, message: string): $CancellablePromise<$models.ConfirmationResult> {
    return $Call.ByID(2168876211, title, message);
}
