// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetDiscordPath(channel: string): $CancellablePromise<string> {
    return $Call.ByID(969922284, channel);
}

export function Install(corePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(523963790, corePaths);
}

export function Repair(corePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(2831752062, corePaths);
}

export function Uninstall(corePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1185527019, corePaths);
}

export function Write(p: string): $CancellablePromise<number> {
    return $Call.ByID(1573621594, p);
}
